// /public/js/data.js
// Dados simples dos estabelecimentos de Peruíbe
// (todas as URLs são opcionais; podem ser preenchidas depois)

window.estabelecimentos = [
  {
    slug: "guarau-praia-suites",
    nome: "Guaraú Praia Suítes",
    tipo: "pousada",
    cidade: "Peruíbe",
    estado: "SP",
    bairro: "Guaraú",
    descricao: "Suítes simples e próximas à praia, ótimo custo-benefício.",
    site: "",
    booking: "",
    maps: "",
    imagem: "/public/img/peruibe-ondeficarbr.jpg",
  },
  {
    slug: "pousada-bicho-preguica",
    nome: "Pousada Bicho Preguiça",
    tipo: "pousada",
    cidade: "Peruíbe",
    estado: "SP",
    bairro: "Guaraú",
    descricao:
      "Tradicional, forte no Booking, ambiente rústico e acolhedor.",
    site: "",
    booking: "",
    maps: "",
    imagem: "/public/img/peruibe-ondeficarbr.jpg",
  },
  {
    slug: "pousada-maktub",
    nome: "Pousada Maktüb",
    tipo: "pousada",
    cidade: "Peruíbe",
    estado: "SP",
    bairro: "Guaraú",
    descricao: "Avaliações excelentes, estilo refúgio perto da natureza.",
    site: "",
    booking: "",
    maps: "",
    imagem: "/public/img/peruibe-ondeficarbr.jpg",
  },
  {
    slug: "pousada-recanto-garca-vermelha",
    nome: "Pousada Recanto Garça Vermelha",
    tipo: "pousada",
    cidade: "Peruíbe",
    estado: "SP",
    bairro: "Guaraú",
    descricao: "Charmosa, silenciosa e próxima da praia.",
    site: "",
    booking: "",
    maps: "",
    imagem: "/public/img/peruibe-ondeficarbr.jpg",
  },
  {
    slug: "sollar-viegas",
    nome: "Sollar Viegas",
    tipo: "pousada",
    cidade: "Peruíbe",
    estado: "SP",
    bairro: "Guaraú",
    descricao: "Propriedade charmosa com excelente custo-benefício.",
    site: "",
    booking: "",
    maps: "",
    imagem: "/public/img/peruibe-ondeficarbr.jpg",
  },
  {
    slug: "waldhaus-eco-pousada",
    nome: "Waldhaus Eco Pousada",
    tipo: "pousada",
    cidade: "Peruíbe",
    estado: "SP",
    bairro: "Juqüia / Natureza",
    descricao: "Ecopousada para desconexão total com a natureza.",
    site: "",
    booking: "",
    maps: "",
    imagem: "/public/img/peruibe-ondeficarbr.jpg",
  },
  {
    slug: "praia-sul-studios",
    nome: "Praia Sul Studios",
    tipo: "flat",
    cidade: "Peruíbe",
    estado: "SP",
    bairro: "Praia Sul",
    descricao: "Studios modernos próximos ao mar.",
    site: "",
    booking: "",
    maps: "",
    imagem: "/public/img/peruibe-ondeficarbr.jpg",
  },
  {
    slug: "pousada-ametista",
    nome: "Pousada Ametista",
    tipo: "pousada",
    cidade: "Peruíbe",
    estado: "SP",
    bairro: "Centro",
    descricao: "Muito procurada, próxima ao centro e serviços.",
    site: "",
    booking: "",
    maps: "",
    imagem: "/public/img/peruibe-ondeficarbr.jpg",
  },
  {
    slug: "pousada-pier-36",
    nome: "Pousada Pier 36",
    tipo: "pousada",
    cidade: "Peruíbe",
    estado: "SP",
    bairro: "Praia do Centro",
    descricao: "Bem próxima ao mar, público fiel, forte em OTAs.",
    site: "",
    booking: "",
    maps: "",
    imagem: "/public/img/peruibe-ondeficarbr.jpg",
  },
  {
    slug: "pousada-peruibiza",
    nome: "Pousada Peruibiza",
    tipo: "pousada",
    cidade: "Peruíbe",
    estado: "SP",
    bairro: "Praia",
    descricao: "Clima jovem, visual instagramável, atmosfera descontraída.",
    site: "",
    booking: "",
    maps: "",
    imagem: "/public/img/peruibe-ondeficarbr.jpg",
  },
  {
    slug: "pousada-canto-da-praia",
    nome: "Pousada Canto da Praia",
    tipo: "pousada",
    cidade: "Peruíbe",
    estado: "SP",
    bairro: "Praia",
    descricao: "Ambiente familiar, fácil acesso à orla.",
    site: "",
    booking: "",
    maps: "",
    imagem: "/public/img/peruibe-ondeficarbr.jpg",
  },
  {
    slug: "villaggio-amanda",
    nome: "Villaggio Amanda",
    tipo: "pousada",
    cidade: "Peruíbe",
    estado: "SP",
    bairro: "Bairro residencial",
    descricao: "Vilas e chalés em ambiente tranquilo.",
    site: "",
    booking: "",
    maps: "",
    imagem: "/public/img/peruibe-ondeficarbr.jpg",
  },
  {
    slug: "pousada-do-guarau",
    nome: "Pousada do Guaraú",
    tipo: "pousada",
    cidade: "Peruíbe",
    estado: "SP",
    bairro: "Guaraú",
    descricao: "Ponto tradicional do bairro, próxima à praia e ao rio.",
    site: "",
    booking: "",
    maps: "",
    imagem: "/public/img/peruibe-ondeficarbr.jpg",
  },
  {
    slug: "pousada-jardim-das-margaridas",
    nome: "Pousada Jardim das Margaridas",
    tipo: "pousada",
    cidade: "Peruíbe",
    estado: "SP",
    bairro: "Bairro tranquilo",
    descricao: "Jardins cuidados e clima romântico.",
    site: "",
    booking: "",
    maps: "",
    imagem: "/public/img/peruibe-ondeficarbr.jpg",
  },
  {
    slug: "hostel-guarau",
    nome: "Hostel Guaraú",
    tipo: "hostel",
    cidade: "Peruíbe",
    estado: "SP",
    bairro: "Guaraú",
    descricao: "Opção econômica com clima de surf e trilhas próximas.",
    site: "",
    booking: "",
    maps: "",
    imagem: "/public/img/peruibe-ondeficarbr.jpg",
  },
  {
    slug: "camping-jureia-surf",
    nome: "Camping Jureia Surf",
    tipo: "camping",
    cidade: "Peruíbe",
    estado: "SP",
    bairro: "Região da Jureia",
    descricao: "Voltado ao público de surf e natureza.",
    site: "",
    booking: "",
    maps: "",
    imagem: "/public/img/peruibe-ondeficarbr.jpg",
  },
  {
    slug: "camping-tia-lola",
    nome: "Camping Tia Lola",
    tipo: "camping",
    cidade: "Peruíbe",
    estado: "SP",
    bairro: "Região de natureza",
    descricao: "Camping tradicional, estrutura simples e receptiva.",
    site: "",
    booking: "",
    maps: "",
    imagem: "/public/img/peruibe-ondeficarbr.jpg",
  },
  {
    slug: "pousada-costa-dourada",
    nome: "Pousada Costa Dourada",
    tipo: "pousada",
    cidade: "Peruíbe",
    estado: "SP",
    bairro: "Praia",
    descricao: "Boa localização para quem quer praia e centro.",
    site: "",
    booking: "",
    maps: "",
    imagem: "/public/img/peruibe-ondeficarbr.jpg",
  },
  {
    slug: "pousada-luz-do-atlantico",
    nome: "Pousada Luz do Atlântico",
    tipo: "pousada",
    cidade: "Peruíbe",
    estado: "SP",
    bairro: "Próximo ao mar",
    descricao: "Conforto simples, clima tranquilo para famílias.",
    site: "",
    booking: "",
    maps: "",
    imagem: "/public/img/peruibe-ondeficarbr.jpg",
  },
  {
    slug: "eco-hostel-jureia",
    nome: "Eco Hostel Jureia",
    tipo: "hostel",
    cidade: "Peruíbe",
    estado: "SP",
    bairro: "Jureia / Natureza",
    descricao:
      "Opção sustentável para quem quer ficar perto das trilhas e rios.",
    site: "",
    booking: "",
    maps: "",
    imagem: "/public/img/peruibe-ondeficarbr.jpg",
  },
];
